build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  to: unused
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: master
  org: app-sre
  repo: aws-resource-exporter
